FROM iot-react:latest

# Clear /app
RUN rm -R /app

# Clone project
RUN git clone -b main https://deployment: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@github.com/Ustalioth/IoT-frontend.git /app
RUN npm i -f

RUN npm run build

CMD [ "npm", "run", "start"]

