version: '3'
services:
  nginx:
    container_name: order-nginx
    build:
      context: .
      dockerfile: nginx/dockerfile
    image: 'collectandverything-nginx'
    restart: unless-stopped
    tty: true
    volumes:
      - './conf/nginx/nginx.conf:/etc/nginx/nginx.conf'
    networks:
      - collectandverything
      - collectandverything-staging
  php-fpm:
    container_name: order-php
    env_file: '.env'
    build:
      context: .
      args:
        - GITLAB_BRANCH=${CI_COMMIT_BRANCH}
      dockerfile: php/dockerfile
    image: 'collectandverything-order:latest'
    restart: unless-stopped
    tty: true
    working_dir: /var/www
    networks:
      - collectandverything
      - collectandverything-staging
networks:
  collectandverything:
    external: true
  collectandverything-staging:
    external: true
