FROM php:8.1-fpm AS collectandverything-php

RUN apt-get update && apt-get install -y \
        supervisor \
        libfreetype6-dev \
        libjpeg62-turbo-dev \
        libpng-dev \
        git \
        curl \
        wget \
        gnupg2 \
        ca-certificates \
        lsb-release \
        apt-transport-https \
        postgresql-client \
        libonig-dev \
        libxml2-dev \
        libcurl4-openssl-dev \
        libzip-dev \
        postgresql-client \
        libssl-dev \
        libpq-dev \
        cron \
        nano \
        libmemcached-dev \
        zlib1g-dev \
        memcached \
    && pecl install memcached

RUN apt-get update && apt-get install -y && docker-php-ext-configure \
    gd --with-freetype --with-jpeg \
    && docker-php-ext-install \
	    -j$(nproc) gd \
	    zip \
	    pdo_pgsql \
	    pgsql \
	    soap \
        sockets \
        bcmath \
    && docker-php-ext-enable \
	    gd \
	    zip \
	    pdo_pgsql \
	    pgsql \
	    soap \
        sockets \
        memcached \
        bcmath \
	&& docker-php-source delete

# Set working directory
WORKDIR /var/www

# Clear cache
RUN apt-get clean && rm -rf /var/lib/apt/lists/*

# Install composer
RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer

RUN curl -OL https://squizlabs.github.io/PHP_CodeSniffer/phpcs.phar
RUN chmod +x phpcs.phar
RUN mv phpcs.phar /usr/local/bin/phpcs

# Require laravel
RUN composer global require "laravel/installer"

# Add user for laravel application
RUN groupadd -g 1000 www
RUN useradd -u 1000 -ms /bin/bash -g www www
