version: '3'

services:
  memcached:
    image: memcached:1.6-alpine
    container_name: memcached
    ports:
      - "11211:11211"
    restart: unless-stopped
    networks:
      - collectandverything
networks:
  collectandverything:
    external: true
