version: '3.7'
services:
  nginx:
    container_name: address-nginx
    image: nginx:1.18-alpine
    restart: unless-stopped
    volumes:
      - './conf/nginx/nginx.conf:/etc/nginx/nginx.conf'
    networks:
      - collectandverything
  php-fpm:
    container_name: address-php
    env_file: '.env'
    build:
      context: .
      args:
        - GITLAB_BRANCH=${CI_COMMIT_BRANCH}
      dockerfile: php/dockerfile
    image: 'collectandverything-address:latest'
    restart: unless-stopped
    tty: true
    working_dir: /var/www
    networks:
      - collectandverything
networks:
  collectandverything:
    external: true
