version: '3'
services:
  db:
    container_name: postgresql
    image: 'postgres:13.2'
    restart: unless-stopped
    ports:
      - '5432:5432'
    command: postgres -c 'max_connections=200'
    environment:
      POSTGRES_USER: collectandverything
      POSTGRES_PASSWORD: 62HnPy4d5S2Dcv
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres/
    networks:
      - iot
networks:
  iot:
    external: true
volumes:
  postgres:
    driver: local
