version: '3'
services:
  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=groupe2
      - RABBITMQ_DEFAULT_PASS=Ym4DcUcTDc5jwB5P
    tty: true
    volumes:
      - '~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/data/'
      - ./conf/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf:ro
      - ./conf/definitions.json:/etc/rabbitmq/definitions.json:ro

    networks:
      - iot
networks:
  iot:
    external: true

