FROM iot-php

# Set PHP configuration
ADD conf/php/php.ini /usr/local/etc/php/

# Set Supervisord configuration
ADD conf/supervisor/supervisord.conf /etc/supervisor/

# Clear /var/www
RUN rm -R /var/www

# Clone project
RUN git clone -b master https://deployment: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@github.com/NicolasGretten/IOT_Gateway.git /var/www

# Setup dependencies
RUN export COMPOSER_ALLOW_SUPERUSER=1

RUN composer install

# Copy existing application directory permissions
RUN chown -R www-data:www-data /var/www

# Copy .env
ADD env/.env /var/www/

# Expose port 9000 for php-fpm
EXPOSE 9000

CMD ["/usr/bin/supervisord"]