version: '3'
services:
  reverse-proxy:
    container_name: proxy
    image: nginx
    restart: unless-stopped
    tty: true
    ports:
      - '80:80'
      - '443:443'
    networks:
      - app-network
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
networks:
  app-network:
    external:
      name: collectandverything
