version: '3'
services:
  reverse-proxy:
    container_name: proxy
    image: nginx
    restart: unless-stopped
    ports:
      - '80:80'
      - '443:443'
    networks:
      - app-network
networks:
  app-network:
    external:
      name: collectandverything
