version: '3'
services:
  reverse-proxy:
    container_name: proxy
    build:
      context: .
      args:
        - GITLAB_BRANCH=${CI_COMMIT_BRANCH}
      dockerfile: nginx-dockerfile
    image: 'collectandverything-proxy:latest'
    restart: unless-stopped
    tty: true
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - './conf/nginx/nginx.conf:/etc/nginx/nginx.conf'
      - './conf/letsencrypt/:/etc/letsencrypt/'
    networks:
      - collectandverything
      - collectandverything-staging
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
networks:
  collectandverything:
    external : true
  collectandverything-staging:
    external : true
