FROM collectandverything-react:latest

# Clone project
ARG GITLAB_BRANCH
RUN git clone -b $GITLAB_BRANCH http://deployment:glpat--z_2WNVnzefZsrxwAMkt@51.178.182.214/collect-verything/front/dashboard-collect-verything.git /app
RUN yarn install

RUN yarn build

CMD [ "yarn", "start"]

