FROM node:14.12.0-alpine # as hopnspace/gatsbyjs:latest

RUN apk add make nasm autoconf automake libtool dpkg pkgconfig libpng libpng-dev g++ git

WORKDIR /app

ENV PATH /app/node_modules/.bin:$PATH

COPY . .

RUN npm cache clean --force

# Clear /app
RUN rm -R /app