version: '3'
services:
  nginx:
    container_name: api-nginx
    build:
      context: .
      dockerfile: nginx/dockerfile
    image: 'nginx:alpine'
    restart: unless-stopped
    tty: true
    volumes:
      - './conf/nginx/nginx.conf:/etc/nginx/nginx.conf'
    networks:
      - collectandverything
  php-fpm:
    container_name: api-php
    env_file: '.env'
    build:
      context: .
      args:
        - GITLAB_BRANCH=${CI_COMMIT_BRANCH}
      dockerfile: php/dockerfile
    image: 'collectandverything-api'
    restart: unless-stopped
    tty: true
    working_dir: /var/www
    networks:
      - collectandverything
networks:
  collectandverything:
    external : true